name: semiuhpe_env
channels:
  - conda-forge
  - defaults
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiofiles=24.1.0
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - cpython=3.10.19
  - cuda-version=11.6
  - cudatoolkit=11.6.2
  - cudnn=8.9.7.29
  - dataclasses=0.8
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - ffmpeg=4.4.0
  - ffmpy=0.3.0
  - freetype=2.14.1
  - fvcore=0.1.5.post20221221
  - gmp=6.3.0
  - gnutls=3.6.13
  - gradio=6.3.0
  - gradio-client=2.0.3
  - groovy-python=0.1.2
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - huggingface_hub=1.3.2
  - hyperframe=6.1.0
  - icu=78.1
  - idna=3.11
  - intel-openmp=2022.1.0
  - iopath=0.1.10
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libdeflate=1.17
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=3.21.12
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libvpx=1.11.0
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - magma=2.5.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - mkl=2022.1.0
  - nccl=2.27.3.1
  - ncurses=6.5
  - nettle=3.6
  - ninja=1.13.2
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.6.0
  - orjson=3.11.5
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.3
  - portalocker=3.2.0
  - pthread-stubs=0.4
  - pydantic=2.11.10
  - pydantic-core=2.33.2
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pydub=0.25.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-gil=3.10.19
  - python-multipart=0.0.21
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch3d=0.7.5
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - ruff=0.14.13
  - safehttpx=0.1.7
  - semantic_version=2.10.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.9.0
  - sniffio=1.3.1
  - starlette=0.50.0
  - tabulate=0.9.0
  - termcolor=3.3.0
  - tk=8.6.13
  - tomli=2.4.0
  - tomlkit=0.13.3
  - tqdm=4.67.1
  - typer=0.21.1
  - typer-slim=0.21.1
  - typer-slim-standard=0.21.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - x264=1!161.3030
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==1.2.4
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mediapipe==0.10.9
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - pillow==12.0.0
      - protobuf==3.20.3
      - pycparser==2.23
      - pyparsing==3.3.1
      - pytorchcv==0.0.73
      - safetensors==0.7.0
      - scipy==1.15.3
      - sounddevice==0.5.3
      - sympy==1.13.1
      - timm==1.0.24
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - triton==3.1.0
      - urllib3==2.6.3
prefix: /home/will/miniconda3/envs/semiuhpe_env
